package ru.lot.entity;

import jakarta.persistence.*;
import lombok.*;
import ru.lot.enums.LotteryName;

@Entity
@Table(name = "lottery_type")
@Getter
@Setter
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class LotteryType extends AbstractEntity<Long> implements Identifiable<Long>  {
    @Column
    @Enumerated(EnumType.STRING)
    private LotteryName name;
    @Column
    private String description;
    @Column
    private Boolean isAutogenerated;
    @Column
    private Double price;
    @Column
    private Double winningAmount;
}
