package ru.lot.entity;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;
import lombok.*;
import ru.lot.enums.LotteryName;

@Entity
@Table(name = "lottery_type")
@Getter
@Setter
@ToString
@NoArgsConstructor
@AllArgsConstructor
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler" })
public class LotteryType extends AbstractEntity<Long> implements Identifiable<Long>  {
    @Column
    @Enumerated(EnumType.STRING)
    private LotteryName name;

    @Column
    private String description;

    @Column
    private Boolean isAutogenerated;

    @Column
    private Double price;

    @Column
    private Double winningAmount;
}
